embedded_components {
  id: "label"
  type: "label"
  data: "text: \"0\"\n"
  "font: \"/builtins/fonts/default.font\"\n"
  "material: \"/builtins/fonts/label.material\"\n"
  "size {\n"
  "  x: 420.0\n"
  "  y: 260.0\n"
  "  z: 0.0\n"
  "}\n"
  "color {\n"
  "  x: 1.0\n"
  "  y: 1.0\n"
  "  z: 1.0\n"
  "  w: 1.0\n"
  "}\n"
  "outline {\n"
  "  x: 0.1\n"
  "  y: 0.18\n"
  "  z: 0.22\n"
  "  w: 1.0\n"
  "}\n"
  "shadow {\n"
  "  x: 0.0\n"
  "  y: 0.0\n"
  "  z: 0.0\n"
  "  w: 0.45\n"
  "}\n"
  "scale {\n"
  "  x: 2.4\n"
  "  y: 2.4\n"
  "  z: 1.0\n"
  "}\n"
  "pivot: PIVOT_CENTER\n"
  "blend_mode: BLEND_MODE_ALPHA\n"
  ""
}
